openapi: 3.0.0
x-stoplight:
  id: zk30b9144hq8c
info:
  version: 1.0.0
  title: Swappily OpenAPI 3.0
  description: API for managing exchange of goods between users.
  license:
    name: MIT
servers:
  - url: 'http://localhost:8080/api/v1'
    description: Localhost
paths:
  /authentications:
    post:
      description: Authenticate a user
      summary: Authenticate a user and return a token.
      responses:
        '200':
          description: Token created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: True if the authentication is a success
                  token:
                    type: string
                    description: JWT token
        '401':
          description: Unauthorized. Invalid credential
      requestBody:
        description: The username and password must be passed in the 'Body
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: Username of the user
                password:
                  type: string
                  description: Password of the user
      x-stoplight:
        id: y6lnq6qeeuh6y
  /users:
    post:
      description: Creates a new user in the system.
      summary: Register a new user.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created. Link in the Location header
          headers:
            Location:
              schema:
                type: string
              description: Link to the newly created user.
        '400':
          description: Bad request. The input is not correct
      x-stoplight:
        id: fjxu6ek9e7nty
    get:
      description: Get all the users. It is possible to show users by their username.
      summary: View all users or filtered by username.
      parameters:
        - in: query
          name: username
          schema:
            type: string
          required: false
      responses:
        '200':
          description: Collection of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '500':
          description: Server error
      x-stoplight:
        id: sfcm9n8d5ek6u
  '/users/{userId}':
    get:
      description: Gets a user by ID.
      summary: View a user
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '500':
          description: Server error
      x-stoplight:
        id: 9rbzpnod84p84
    delete:
      description: Delete an user
      summary: Delete an user.
      security:
        - TokenQueryAuth: []
        - accessTokenHeader: []
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: User deleted
        '404':
          description: User not found
        '500':
          description: Server error
      x-stoplight:
        id: 9uo75co78uiyd
    put:
      description: Updates an existing user.
      summary: Update an existing user
      security:
        - TokenQueryAuth: []
        - accessTokenHeader: []
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated
        '404':
          description: User not found
      x-stoplight:
        id: 68pk8lzqlqvcy
  /listings:
    post:
      description: Creates a new listing.
      summary: Create a new listing
      security:
        - TokenQueryAuth: []
        - accessTokenHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Listing'
      responses:
        '201':
          description: Listing created. Link in the Location header
          headers:
            Location:
              schema:
                type: string
              description: Link to the newly created listing.
      x-stoplight:
        id: v25x1q7izo1kb
    get:
      description: 'Gets the list of listings. It is possible to show the listing by their title or filtered by favorites, followed or status.'
      summary: View all listings or filtered listings.
      parameters:
        - in: query
          name: title
          schema:
            type: string
        - in: query
          name: status
          schema:
            type: array
            items:
              type: string
            enum:
              - As new
              - Good
              - Ok
              - Not Good
        - in: query
          name: favorite
          schema:
            type: boolean
        - in: query
          name: followed
          schema:
            type: boolean
      responses:
        '200':
          description: Collection of listings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Listing'
        '404':
          description: Not found
        '500':
          description: Server error
      x-stoplight:
        id: ptsqe6xnbvb33
  '/listings/{listingId}':
    get:
      description: Gets a listing by ID.
      summary: View a listing
      parameters:
        - in: path
          name: listingId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Listing found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
        '404':
          description: Listing not found
      x-stoplight:
        id: l18m3t6a2a81d
    delete:
      description: Deletes a listing by ID.
      summary: Delete a listing
      security:
        - TokenQueryAuth: []
        - accessTokenHeader: []
      parameters:
        - in: path
          name: listingId
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Listing deleted
        '403':
          description: The user does not have the authorization
        '404':
          description: Listing not found
        '500':
          description: Internal server error
      x-stoplight:
        id: hhbfxz19wavn5
    put:
      description: Updates an existing listing.
      summary: Update an existing listing
      security:
        - TokenQueryAuth: []
        - accessTokenHeader: []
      parameters:
        - in: path
          name: listingId
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Listing'
      responses:
        '200':
          description: Listing modified
        '404':
          description: Listing not found
      x-stoplight:
        id: 9tkvaq3k652dv
  /exchange:
    get:
      description: Gets the list of exchanges. It is possible to show the exchanges by their status.
      summary: View all exchanges or filtered exchanges.
      parameters:
        - in: query
          name: status
          schema:
            type: array
            items:
              type: string
            enum:
              - pending
              - accepted
              - rejected
      responses:
        '200':
          description: Collection of exchanges
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exchange'
        '404':
          description: Exchanges not found
      x-stoplight:
        id: pz72gepzxjqm7
  '/exchange/listing/{listingId}':
    post:
      description: Creates a new exchange.
      summary: Exchange an object
      security:
        - TokenQueryAuth: []
        - accessTokenHeader: []
      parameters:
        - in: path
          name: listingId
          schema:
            type: string
          required: true
      responses:
        '201':
          description: Exchange created. Link in the Location header
          headers:
            Location:
              schema:
                type: string
              description: Link to the newly created exchange.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exchange'
      x-stoplight:
        id: rz90tzdtusqj1
  '/exchange/{exchangeId}':
    get:
      description: Gets an exchange by ID.
      summary: View an exchange
      parameters:
        - in: path
          name: exchangeId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Exchange found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exchange'
        '404':
          description: Exchange not found
      x-stoplight:
        id: x0a2y30d3av84
    put:
      description: Modify an exchange
      summary: Modify an exchange
      security:
        - TokenQueryAuth: []
        - accessTokenHeader: []
      parameters:
        - in: path
          name: exchangeId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Exchange modified
        '404':
          description: Exchange not found
      x-stoplight:
        id: v9li0ergdbuon
    delete:
      description: '''Deleting an existing exchange'''
      summary: Deleting an exchange
      parameters:
        - in: path
          name: exchangeId
          schema:
            type: string
          required: true
      security:
        - TokenQueryAuth: []
        - accessTokenHeader: []
      responses:
        '204':
          description: Exchange deleted
        '404':
          description: Exchange not found
      x-stoplight:
        id: u8k57cg9ri9a0
  /review:
    post:
      description: '''Create a new review'''
      summary: Write a review
      security:
        - TokenQueryAuth: []
        - accessTokenHeader: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '201':
          description: '''Review created. The header contains a link to the newliy created review'''
          headers:
            Location:
              schema:
                type: string
              description: Link to the newly created review.
      x-stoplight:
        id: hs9crfslb2mxw
  '/review/{reviewId}':
    delete:
      description: '''The user deletes one of his revews'''
      summary: Deleting a revew
      security:
        - TokenQueryAuth: []
        - accessTokenHeader: []
      parameters:
        - in: path
          name: reviewId
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Review deleted
        '403':
          description: This user does not have the authorizatuon
        '404':
          description: Review not found
      x-stoplight:
        id: rkw39va24nc9t
  '/review/reviewee/{revieweeId}':
    get:
      description: Get all the review of one user
      summary: Reviews of an user
      parameters:
        - in: header
          name: authenticate
          schema:
            type: string
        - in: path
          name: revieweeId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Reviews find
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Review'
        '404':
          description: Not found
        '500':
          description: Server error
      x-stoplight:
        id: 2y39wyme3ew7d
  '/report/{Id}':
    post:
      description: Creating a new report
      summary: Create a report
      parameters:
        - in: header
          name: authenticate
          schema:
            type: string
        - in: path
          name: Id
          schema:
            type: string
          required: true
      responses:
        '201':
          description: Report created
        '404':
          description: Not found
        '500':
          description: Server error
      x-stoplight:
        id: uoper50c9xunx
components:
  securitySchemes:
    accessTokenHeader:
      description: The API authentication. The API key must be a valid JWT token.
      type: apiKey
      in: header
      name: x-access-token
    TokenQueryAuth:
      description: The APi authentication. The API must be a valid JWT token'
      type: apiKey
      in: query
      name: token
  schemas:
    User:
      type: object
      required:
        - name
        - userId
        - surname
        - username
        - email
        - password
        - usertype
        - favorite
        - followed
        - n_followed
        - followers
        - n_followers
        - blocklist
        - n_exchanges
      properties:
        name:
          type: string
          description: Name of the user
        userId:
          type: integer
        surname:
          type: string
          description: Name of the user
        username:
          type: string
          minLength: 3
          maxLength: 20
          description: Username of the user
        email:
          type: string
          description: Email address of the user
        password:
          type: string
          minLength: 8
          description: Password of the user
        usertype:
          type: string
          enum: [user, operator]
          description: Indicates whether the user is a normal user or an operator
        phone:
          type: string
          description: Phone number of the user
        favorite:
          type: array
          description: List of favorite listings of the user
          items:
            type: string
            description: Ids of the favorite listings 
          default: []
        followed:
          type: array
          items:
            type: string
          description: List of followed users
          default: []
        n_followed:
          type: integer
          description: Number of users followed by the user
        followers:
          type: array
          description: List of followers of the user 
          items:
            type: string
            description: Ids of the followers
          default: []
        n_followers:
          type: integer
          description: Number of followers of the user
        blocklist:
          type: array
          description: List of users blocked by the user
          items:
            type: string
            description: Ids of the blocked users
          default: []
        n_exchanges:
          type: integer
          description: Number of exchanges made by the user
      x-stoplight:
        id: jlrd3bu8k2a0d
    Listing:
      type: object
      required:
        - title
        - userId
        - username
        - description
        - status
        - available
      properties:
        title:
          type: string
          description: Title of the listing
        userId:
          type: string
          description: Identification code of the user
        username:
          type: string
          description: Username of the creator of the listing
        description:
          type: string
          description: Description of the listing
        status:
          type: string
          enum:
            - As new
            - Good
            - Ok
            - Not Good
          description: Physical condition of the object
        available:
          type: boolean
          description: Availability of the object
      x-stoplight:
        id: 221d3mf53a0ez
    Exchange:
      type: object
      required:
        - sender
        - receiver
        - offeredListing
        - requestedListing
        - status
        - date
      properties:
        sender:
          type: string
          format: objectId
          description: Link to the user who initiated the exchange
        receiver:
          type: string
          format: objectId
          description: Link to the user who initiated the exchange
        offeredListing:
          type: string
          format: objectId
          description: Link to the listing
        requestedListing:
          type: string
          format: objectId
          description: Reference to the listing requested in the exchange
        status:
          type: string
          enum:
            - pending
            - accepted
            - rejected
          description: Status of the exchange
        date:
          type: string
          format: date-time
          description: Date when the exchange was created
      x-stoplight:
        id: wv6hktdojgdt4
    Review:
      type: object
      required:
        - reviewId
        - revieweeId
        - reviewerId
        - text
      properties:
        reviewId:
          type: integer
          format: objectId
          description: Id of the review
        reviewerId:
          type: string
          format: objectId
          description: Id of the user writing the review
        revieweeId:
          type: string
          format: objectId
          description: Id of the user being reviewed
        text:
          type: string
          format: objectId
          description: Body of the review
      x-stoplight:
        id: f7t8et4y946gv
    Report:
      type: object
      required:
        - reportId
        - reporterId
        - reporteeId
        - listingId
        - text
      properties:
        reportId:
          type: integer
          description: Id of the report
        reporterId:
          type: integer
          description: Id of the user author of the report
        reporteeId:
          type: string
          description: Id of the user reported
        listingId:
          type: string
          description: Id of the listing reported
        text:
          type: string
          description: Textual description of the report
      x-stoplight:
        id: ao0e8ptncc0y7
